import { ChangeDetectionStrategy, ChangeDetectorRef, Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { finalize } from 'rxjs';
import { SettingsService } from '../../core/services/settings.service';
import { SystemSettings } from '../../core/models/settings.models';

@Component({
  selector: 'app-settings', standalone: true, imports: [CommonModule, FormsModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="settings-page">
      <div class="page-header"><div><span class="eyebrow">Administration</span><h2>System Settings</h2><p>Database-backed call center configuration. Changes are audited and apply to future operational workflows.</p></div>
      <div class="header-actions"><button class="button secondary" [disabled]="loading || saving" (click)="load()">Refresh</button><button class="button danger" [disabled]="loading || saving" (click)="reset()">Restore defaults</button><button class="button primary" [disabled]="loading || saving || !settings" (click)="save()">{{ saving ? 'Saving…' : 'Save changes' }}</button></div></div>
      @if (error) { <div class="error-banner">{{ error }}</div> }
      @if (message) { <div class="success-banner">{{ message }}</div> }
      @if (loading) { <div class="state-card">Loading system configuration…</div> }
      @if (settings && !loading) { <div class="settings-grid">
        <section class="card"><h3>General</h3><label>Call center name<input [(ngModel)]="settings.general.callCenterName"></label><label>Operating hours<input [(ngModel)]="settings.general.operatingHours"></label><label>Support email<input type="email" [(ngModel)]="settings.general.supportEmail"></label><label>Default locale<input [(ngModel)]="settings.general.defaultLocale"></label><label>Timezone<input [(ngModel)]="settings.general.timezone"></label></section>
        <section class="card"><h3>Call settings</h3><label>Ring timeout (seconds)<input type="number" min="5" max="600" [(ngModel)]="settings.call.ringTimeoutSeconds"></label><label>Maximum call duration (minutes)<input type="number" min="1" max="1440" [(ngModel)]="settings.call.maxCallDurationMinutes"></label><label class="toggle"><input type="checkbox" [(ngModel)]="settings.call.autoAssignmentEnabled"> Auto assignment</label><label class="toggle"><input type="checkbox" [(ngModel)]="settings.call.recordingEnabled"> Recording enabled</label><label class="toggle"><input type="checkbox" [(ngModel)]="settings.call.allowCallTransfer"> Allow call transfer</label><label class="toggle"><input type="checkbox" [(ngModel)]="settings.call.requireDisposition"> Require disposition</label></section>
        <section class="card"><h3>Queue settings</h3><label>Queue timeout (seconds)<input type="number" min="10" max="86400" [(ngModel)]="settings.queue.maxQueueWaitSeconds"></label><label>Maximum queue capacity<input type="number" min="1" max="10000" [(ngModel)]="settings.queue.maxQueueCapacity"></label><label>Queue timeout behavior<select [(ngModel)]="settings.queue.queueTimeoutAction"><option>Abandon</option><option>Voicemail</option><option>Transfer</option></select></label><label class="toggle"><input type="checkbox" [(ngModel)]="settings.queue.priorityRoutingEnabled"> Priority routing</label><label class="toggle"><input type="checkbox" [(ngModel)]="settings.queue.announceQueuePosition"> Announce queue position</label></section>
        <section class="card"><h3>Notifications</h3><label>Queue wait alert (seconds)<input type="number" min="1" max="86400" [(ngModel)]="settings.notification.queueWaitAlertThresholdSeconds"></label><label class="toggle"><input type="checkbox" [(ngModel)]="settings.notification.soundAlertsEnabled"> Sound alerts</label><label class="toggle"><input type="checkbox" [(ngModel)]="settings.notification.missedCallAlertsEnabled"> Missed-call alerts</label><label class="toggle"><input type="checkbox" [(ngModel)]="settings.notification.desktopNotificationsEnabled"> Desktop notifications</label></section>
        <section class="card"><h3>Security</h3><label>Session timeout (minutes)<input type="number" min="5" max="1440" [(ngModel)]="settings.security.sessionTimeoutMinutes"></label><label>Maximum login attempts<input type="number" min="1" max="20" [(ngModel)]="settings.security.maxLoginAttempts"></label><label class="toggle"><input type="checkbox" [(ngModel)]="settings.security.requireStrongPassword"> Require strong passwords</label><label class="toggle"><input type="checkbox" [(ngModel)]="settings.security.auditLoggingEnabled"> Audit logging</label><label class="toggle"><input type="checkbox" [(ngModel)]="settings.security.restrictAgentOutbound"> Restrict agent outbound calls</label></section>
      </div> }
  </div>`,
  styles: [`.header-actions{display:flex;gap:8px;align-items:center}.button{border:0;border-radius:8px;padding:10px 14px;font-weight:700;cursor:pointer}.primary{background:#0d1628;color:white}.secondary{background:#e2e8f0;color:#172033}.danger{background:#fee2e2;color:#991b1b}.settings-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px;margin-top:24px}.card{background:#fff;border:1px solid #e2e8f0;border-radius:12px;padding:20px}.card h3{margin-top:0}.card label{display:block;font-size:13px;font-weight:650;margin:14px 0}.card input:not([type=checkbox]),.card select{display:block;width:100%;margin-top:6px;border:1px solid #cbd5e1;border-radius:7px;padding:9px;background:white}.card label.toggle{font-weight:500}.card label.toggle input{margin-right:8px}.success-banner{margin-top:18px;padding:11px 12px;background:#ecfdf5;border:1px solid #a7f3d0;color:#166534;border-radius:8px}@media(max-width:850px){.settings-grid{grid-template-columns:1fr}.header-actions{flex-wrap:wrap}}`]
})
export class SettingsComponent implements OnInit {
  private readonly service = inject(SettingsService); private readonly cdr = inject(ChangeDetectorRef);
  settings: SystemSettings | null = null; loading = false; saving = false; error = ''; message = '';
  ngOnInit(): void { this.load(); }
  load(): void { this.loading = true; this.error = ''; this.service.getAll().pipe(finalize(() => { this.loading = false; this.cdr.markForCheck(); })).subscribe({ next: s => this.settings = s, error: e => this.error = e?.error?.message || 'Unable to load system settings.' }); }
  save(): void { if (!this.settings) return; this.saving = true; this.error = ''; this.message = ''; this.service.update(this.settings).pipe(finalize(() => { this.saving = false; this.cdr.markForCheck(); })).subscribe({ next: s => { this.settings = s; this.message = 'System settings saved.'; }, error: e => this.error = e?.error?.message || 'Unable to save settings.' }); }
  reset(): void { if (!confirm('Restore all system settings to their database defaults?')) return; this.saving = true; this.error = ''; this.service.reset().pipe(finalize(() => { this.saving = false; this.cdr.markForCheck(); })).subscribe({ next: s => { this.settings = s; this.message = 'Defaults restored.'; }, error: e => this.error = e?.error?.message || 'Unable to restore defaults.' }); }
}
